import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-m-news-channel',
  templateUrl: './m-news-channel.component.html',
  styleUrls: ['./m-news-channel.component.scss']
})
export class MNewsChannelComponent implements OnInit {

  constructor() { }
  public windTitle:String="News Channel";
  public selectedItem:any="";
  public channel=[
    {title: "ABC News", code: "us", category: "general"},
    {title: "ABC News (AU)", code: "au", category: "general"},
    {title: "Aftenposten", code: "no", category: "general"},
    {title: "Al Jazeera English", code: "us", category: "general"},
    {title: "ANSA.it", code: "it", category: "general"},
    {title: "Argaam", code: "sa", category: "business"},
    {title: "Ars Technica", code: "us", category: "technology"},
    {title: "Ary News", code: "pk", category: "general"},
    {title: "Associated Press", code: "us", category: "general"},
    {title: "Australian Financial Review", code: "au", category: "business"},
    {title: "Axios", code: "us", category: "general"},
    {title: "BBC News", code: "gb", category: "general"},
    {title: "BBC Sport", code: "gb", category: "sports"},
    {title: "Bild", code: "de", category: "general"},
    {title: "Blasting News (BR)", code: "br", category: "general"},
    {title: "Bleacher Report", code: "us", category: "sports"},
    {title: "Bloomberg", code: "us", category: "business"},
    {title: "Breitbart News", code: "us", category: "general"},
    {title: "Business Insider", code: "us", category: "business"},
    {title: "Business Insider (UK)", code: "gb", category: "business"},
    {title: "Buzzfeed", code: "us", category: "entertainment"},
    {title: "CBC News", code: "ca", category: "general"},
    {title: "CBS News", code: "us", category: "general"},
    {title: "CNBC", code: "us", category: "business"},
    {title: "CNN", code: "us", category: "general"},
    {title: "CNN Spanish", code: "us", category: "general"},
    {title: "Crypto Coins News", code: "us", category: "technology"},
    {title: "Daily Mail", code: "gb", category: "entertainment"},
    {title: "Der Tagesspiegel", code: "de", category: "general"},
    {title: "Die Zeit", code: "de", category: "business"},
    {title: "El Mundo", code: "es", category: "general"},
    {title: "Engadget", code: "us", category: "technology"},
    {title: "Entertainment Weekly", code: "us", category: "entertainment"},
    {title: "ESPN", code: "us", category: "sports"},
    {title: "ESPN Cric Info", code: "us", category: "sports"},
    {title: "Financial Post", code: "ca", category: "business"},
    {title: "Focus", code: "de", category: "general"},
    {title: "Football Italia", code: "it", category: "sports"},
    {title: "Fortune", code: "us", category: "business"},
    {title: "FourFourTwo", code: "gb", category: "sports"},
    {title: "Fox News", code: "us", category: "general"},
    {title: "Fox Sports", code: "us", category: "sports"},
    {title: "Globo", code: "br", category: "general"},
    {title: "Google News", code: "us", category: "general"},
    {title: "Google News (Argentina)", code: "ar", category: "general"},
    {title: "Google News (Australia)", code: "au", category: "general"},
    {title: "Google News (Brasil)", code: "br", category: "general"},
    {title: "Google News (Canada)", code: "ca", category: "general"},
    {title: "Google News (France)", code: "fr", category: "general"},
    {title: "Google News (India)", code: "in", category: "general"},
    {title: "Google News (Israel)", code: "is", category: "general"},
    {title: "Google News (Italy)", code: "it", category: "general"},
    {title: "Google News (Russia)", code: "ru", category: "general"},
    {title: "Google News (Saudi Arabia)", code: "sa", category: "general"},
    {title: "Google News (UK)", code: "gb", category: "general"},
    {title: "Göteborgs-Posten", code: "se", category: "general"},
    {title: "Gruenderszene", code: "de", category: "technology"},
    {title: "Hacker News", code: "us", category: "technology"},
    {title: "Handelsblatt", code: "de", category: "business"},
    {title: "IGN", code: "us", category: "entertainment"},
    {title: "Il Sole 24 Ore", code: "it", category: "business"},
    {title: "Independent", code: "gb", category: "general"},
    {title: "Infobae", code: "ar", category: "general"},
    {title: "InfoMoney", code: "br", category: "business"},
    {title: "La Gaceta", code: "ar", category: "general"},
    {title: "La Nacion", code: "ar", category: "general"},
    {title: "La Repubblica", code: "it", category: "general"},
    {title: "Le Monde", code: "fr", category: "general"},
    {title: "Lenta", code: "ru", category: "general"},
    {title: "L'equipe", code: "fr", category: "sports"},
    {title: "Les Echos", code: "fr", category: "business"},
    {title: "Libération", code: "fr", category: "general"},
    {title: "Marca", code: "es", category: "sports"},
    {title: "Mashable", code: "us", category: "entertainment"},
    {title: "Medical News Today", code: "us", category: "health"},
    {title: "Metro", code: "gb", category: "general"},
    {title: "Mirror", code: "gb", category: "general"},
    {title: "MSNBC", code: "us", category: "general"},
    {title: "MTV News", code: "us", category: "entertainment"},
    {title: "MTV News (UK)", code: "gb", category: "entertainment"},
    {title: "National Geographic", code: "us", category: "science"},
    {title: "National Review", code: "us", category: "general"},
    {title: "NBC News", code: "us", category: "general"},
    {title: "News24", code: "za", category: "general"},
    {title: "New Scientist", code: "us", category: "science"},
    {title: "News.com.au", code: "au", category: "general"},
    {title: "Newsweek", code: "us", category: "general"},
    {title: "New York Magazine", code: "us", category: "general"},
    {title: "Next Big Future", code: "us", category: "science"},
    {title: "NFL News", code: "us", category: "sports"},
    {title: "NHL News", code: "us", category: "sports"},
    {title: "NRK", code: "no", category: "general"},
    {title: "Politico", code: "us", category: "general"},
    {title: "Polygon", code: "us", category: "entertainment"},
    {title: "RBC", code: "ru", category: "general"},
    {title: "Recode", code: "us", category: "technology"},
    {title: "Reddit /r/all", code: "us", category: "general"},
    {title: "Reuters", code: "us", category: "general"},
    {title: "RT", code: "ru", category: "general"},
    {title: "RTE", code: "ie", category: "general"},
    {title: "RTL Nieuws", code: "nl", category: "general"},
    {title: "SABQ", code: "sa", category: "general"},
    {title: "Spiegel Online", code: "de", category: "general"},
    {title: "Svenska Dagbladet", code: "se", category: "general"},
    {title: "T3n", code: "de", category: "technology"},
    {title: "TalkSport", code: "gb", category: "sports"},
    {title: "TechCrunch", code: "us", category: "technology"},
    {title: "TechCrunch (CN)", code: "zh", category: "technology"},
    {title: "TechRadar", code: "us", category: "technology"},
    {title: "The American Conservative", code: "us", category: "general"},
    {title: "The Globe And Mail", code: "ca", category: "general"},
    {title: "The Hill", code: "us", category: "general"},
    {title: "The Hindu", code: "in", category: "general"},
    {title: "The Huffington Post", code: "us", category: "general"},
    {title: "The Irish Times", code: "ie", category: "general"},
    {title: "The Jerusalem Post", code: "is", category: "general"},
    {title: "The Lad Bible", code: "gb", category: "entertainment"},
    {title: "The New York Times", code: "us", category: "general"},
    {title: "The Next Web", code: "us", category: "technology"},
    {title: "The Sport Bible", code: "gb", category: "sports"},
    {title: "The Telegraph", code: "gb", category: "general"},
    {title: "The Times of India", code: "in", category: "general"},
    {title: "The Verge", code: "us", category: "technology"},
    {title: "The Wall Street Journal", code: "us", category: "business"},
    {title: "The Washington Post", code: "us", category: "general"},
    {title: "The Washington Times", code: "us", category: "general"},
    {title: "Time", code: "us", category: "general"},
    {title: "USA Today", code: "us", category: "general"},
    {title: "Vice News", code: "us", category: "general"},
    {title: "Wired", code: "us", category: "technology"},
    {title: "Wired.de", code: "de", category: "technology"},
    {title: "Wirtschafts Woche", code: "de", category: "business"},
    {title: "Xinhua Net", code: "zh", category: "general"},
    {title: "Ynet", code: "is", category: "general"}
  ];
  listClick(event, newValue) {
    this.selectedItem = newValue;  // don't forget to update the model here
    console.log("you clicked");
    console.log(newValue);
  }  
  ngOnInit() {
  }
}